### ISSUE TITLE
使用MySQL的报错

### ISSUE THREAD

**Issue by Soldier233** [weihao/EnchantmentsEnhance#185]
### What behaviour is observed:
MySQL报错

### Steps to reproduce:
运行mysql模式，进行任何相关数据存储的操作，等待一定的时间，即可触发该错误

### Plugin list:
``` Plugins (2): DouYuUHC, EnchantmentsEnhance```

### Environment description
v1_12_R1 Spigot

### Enchantments Enhance build number:
v7.9.3

### Error Log:
```
[23:25:15 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`playername` = 'Soldier__'' at line 1
[23:25:15 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:25:15 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:25:15 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:25:15 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:25:15 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[23:25:15 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[23:25:15 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[23:25:15 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[23:25:15 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[23:25:15 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[23:25:15 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[23:25:15 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[23:25:15 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[23:25:15 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[23:25:15 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[23:25:15 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[23:25:15 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[23:25:15 WARN]:        at org.pixeltime.enchantmentsenhance.mysql.DataStorage.saveStats(DataStorage.java:84)
[23:25:15 WARN]:        at org.pixeltime.enchantmentsenhance.listener.PlayerStreamListener$1.run(PlayerStreamListener.java:62)
[23:25:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[23:25:15 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[23:25:15 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[23:25:15 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[23:25:15 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[23:25:15 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[23:25:15 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by weihao** [comment]
Related to https://github.com/weihao/EnchantmentsEnhance/issues/142

**Comment by Soldier233** [comment]
```
[19:38:20 INFO]: Soldier__ issued server command: /enhance give Soldier__
[19:38:21 INFO]: Soldier__ issued server command: /enhance give Soldier__ 1
[19:38:25 INFO]: Soldier__ issued server command: /enhance give Soldier__ 1 10000
[19:44:18 INFO]: Soldier__ lost connection: Disconnected
[19:44:18 INFO]: Soldier__ left the game
[19:44:19 INFO]: com.mysql.jdbc.JDBC42PreparedStatement@646dafb: UPDATE `enchantmentsenhance` SET `failstack` = 0, `items` = '[0, 10000, 0, 0, 0]', `valks` = '[]', `grind` = 2WHERE `playername` = 'Soldier__';
[19:44:19 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`playername` = 'Soldier__'' at line 1
[19:44:19 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:44:19 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:44:19 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:44:19 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:44:19 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[19:44:19 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[19:44:19 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[19:44:19 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[19:44:19 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[19:44:19 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[19:44:19 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[19:44:19 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[19:44:19 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[19:44:19 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[19:44:19 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[19:44:19 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[19:44:19 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[19:44:19 WARN]:        at org.pixeltime.enchantmentsenhance.mysql.DataStorage.saveStats(DataStorage.java:84)
[19:44:19 WARN]:        at org.pixeltime.enchantmentsenhance.listener.PlayerStreamListener$1.run(PlayerStreamListener.java:62)
[19:44:19 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[19:44:19 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[19:44:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[19:44:19 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:44:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:44:19 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:44:19 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Tried to print the PreparedStatement and it turns out that a space is missing in the sql.  
The space added and it seems works fine.  

Pull request related to this bug will be sent later.  

### And here comes the suggestions about mysql table  
![image](https://user-images.githubusercontent.com/22394506/72680474-3cd1c380-3af5-11ea-813e-33db6ccc1e01.png)
Above is the structure of your table.  
As you can see, the column ```playername``` has the length of 256.  
In some mysql versions, it will go wrong because the length of your index is too long.  
Here are my solutions:(Too lazy to modify the code for you)  

- Add playername as primary key and remove all your index.(Because mysql will create a index for you by default as long as you set the column as primary key)  
- The default encoding of utf8 is recomended when creating the table.
- Use text rather than varchar in ```items,valks```(It will lose data when the length of string is too big)

**Comment by weihao** [comment]
Thanks a lot for the feedback!

Your suggestions are implemented and merged into the master.
