### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by weihao** [weihao/EnchantmentsEnhance#197]
```
[14:00:56] [Server thread/INFO]: AxinGG issued server command: /enhance menu
[14:00:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/util/ItemBuilder
        at org.pixeltime.enchantmentsenhance.gui.menu.icons.EnhanceIcon.getItem(EnhanceIcon.java:17) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:242) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:61) ~[?:?]
        at org.pixeltime.enchantmentsenhance.command.player.MenuCommand.onCommand(MenuCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
[14:01:00] [Server thread/INFO]: AxinGG issued server command: /enhance menu AxinGG
[14:01:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/util/ItemBuilder
        at org.pixeltime.enchantmentsenhance.gui.menu.icons.EnhanceIcon.getItem(EnhanceIcon.java:17) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:242) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:61) ~[?:?]
        at org.pixeltime.enchantmentsenhance.command.player.MenuCommand.onCommand(MenuCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
[14:01:08] [Server thread/INFO]: AxinGG issued server command: /enhance inventory
[14:01:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/gui/menu/ItemMenu
        at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:137) ~[PluginClassLoader.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[PluginClassLoader.class:git-CatServer-1.12.2-1b57158]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[PluginClassLoader.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[PluginClassLoader.class:git-CatServer-1.12.2-1b57158]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
[14:02:21] [Craft Scheduler Thread - 37/INFO]: [XConomy] 数据库缓存已保存 >>> 2 条
[14:03:29] [Server thread/INFO]: AxinGG issued server command: /enhance list
>
>
>
[14:05:29] [Server thread/INFO]: AxinGG issued server command: /enhance help
[14:05:34] [Server thread/INFO]: AxinGG issued server command: /enhance inventory
[14:05:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/gui/menu/ItemMenu
        at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
[14:05:36] [Server thread/INFO]: AxinGG issued server command: /enhance inventory
[14:05:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/gui/menu/ItemMenu
        at org.pixeltime.enchantmentsenhance.command.player.InventoryCommand.onCommand(InventoryCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
[14:05:42] [Server thread/INFO]: AxinGG issued server command: /enhance menu
[14:05:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'enhance' in plugin EnchantmentsEnhance v7.9.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[SimpleCommandMap.class:git-CatServer-1.12.2-1b57158]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServer-1.12.2-1b57158]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/pixeltime/enchantmentsenhance/util/ItemBuilder
        at org.pixeltime.enchantmentsenhance.gui.menu.icons.EnhanceIcon.getItem(EnhanceIcon.java:17) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:242) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:61) ~[?:?]
        at org.pixeltime.enchantmentsenhance.command.player.MenuCommand.onCommand(MenuCommand.kt:14) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.CommandManager.onCommand(CommandManager.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-1b57158]
        ... 15 more
>
```

**Comment by weihao** [comment]
Related issue:
```
[23:04:42 WARN]: java.lang.ClassNotFoundException: org.pixeltime.enchantmentsenhance.util.ItemBuilder
[23:04:42 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[23:04:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:04:42 WARN]:        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[23:04:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:04:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124)
[23:04:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[23:04:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:04:42 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[23:04:42 WARN]:        at org.pixeltime.enchantmentsenhance.gui.menu.icons.EnhanceIcon.getItem(EnhanceIcon.java:17)
[23:04:42 WARN]:        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:242)
[23:04:42 WARN]:        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.<init>(MainMenu.java:61)
[23:04:42 WARN]:        at org.pixeltime.enchantmentsenhance.listener.VanillaEnchantListener.onOpenEnchantmentTable(VanillaEnchantListener.java:42)
[23:04:42 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source)
[23:04:42 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[23:04:42 WARN]:        at pw.yumc.Yum.inject.ListenerInjector.execute(ListenerInjector.java:88)
[23:04:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[23:04:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[23:04:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331)
[23:04:42 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:501)
[23:04:42 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1142)
[23:04:42 WARN]:        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61)
[23:04:42 WARN]:        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13)
[23:04:42 WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:04:42 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:04:42 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[23:04:42 WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:04:42 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850)
[23:04:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
[23:04:42 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
[23:04:42 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
[23:04:42 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by weihao** [comment]
See https://github.com/weihao/EnchantmentsEnhance/issues/179
