### ISSUE TITLE
经常报错

### ISSUE THREAD

**Issue by Q2297045667** [weihao/EnchantmentsEnhance#198]
### What behaviour is observed:
俺也不晓得

### Steps to reproduce:
正常运行当中

### Plugin list:
Plugins (52): EntityTrackerFixer, AegisClear, PlaceholderAPI, Oh_the_dungeons_youll_go, SkinsRestorer, Chenghao, LightAPI, LuckPerms, Chair, OpenInv, SAML, LoginSecurity, VillagerOptimiser, spark, ProtocolLib, Notbuild, PocketGames, GeoFurnace, LangUtils, CS-CoreLib, mcMMO, Vault, MiaoChat, HolographicDisplays, Dantiao, BossShopPro, Companions, WorldEdit, Essentials, Civs, Citizens, EssentialsChat, SuperVanish, McPay, PlotSquared, WorldGuard, EssentialsProtect, CitizensGUI, EssentialsSpawn, CoreProtect, TitleManager, TempFly, EnchantmentsEnhance, Admin-GUI, Elevator, Multiverse-Core, FogusCore, AncientGates, EliteMobs, QuickShop, LockettePro, AdvancedFood

### Environment description
spigot-1.15.2-112

### Enchantments Enhance build number:
7.9.10

### Error Log:
[05:31:45] [Server thread/INFO]: [EnchantmentsEnhance] Disabling EnchantmentsEnhance v7.9.10
[05:31:45] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: ee
[05:31:45] [Server thread/ERROR]: Error occurred while disabling EnchantmentsEnhance v7.9.10 (Is it up to date?)
java.lang.NullPointerException: null
        at org.pixeltime.enchantmentsenhance.mysql.DataStorage.saveStats(DataStorage.java:53) ~[?:?]
        at org.pixeltime.enchantmentsenhance.Main.onDisable(Main.java:319) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:445) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:398) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:696) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by weihao** [comment]
请贴出全部日记

**Comment by Q2297045667** [comment]
更换JAVA8之后就好多了虽然有的时候还是会出现空指针
可能是我服务端配置的问题这两天在做新的服

**Comment by Q2297045667** [comment]
刚说完没多久，关服的时候报错
[05:06:21] [Server thread/INFO]: Stopping the server
[05:06:21] [Server thread/INFO]: 未知的命令。 输入“/help”以获得帮助.
[05:06:21] [Server thread/INFO]: 未知的命令。 输入“/help”以获得帮助.
[05:06:21] [Server thread/INFO]: Stopping server
[05:06:21] [Server thread/INFO]: [AdvancedFood] Disabling AdvancedFood v3.6.3
[05:06:21] [Server thread/INFO]: [AdvancedFood] Recipe unregistered: 'lemon' !
[05:06:21] [Server thread/INFO]: [AdvancedFood] Recipe unregistered: 'burger' !
[05:06:21] [Server thread/INFO]: [AdvancedFood] Recipe unregistered: 'candy_bread' !
[05:06:21] [Server thread/INFO]: [AdvancedFood] Recipe unregistered: 'coca_cola' !
[05:06:21] [Server thread/INFO]: [QuantumShop] Disabling QuantumShop v3.6.8
[05:06:21] [Server thread/INFO]: [QuantumShop] Unloaded module: Chest Shop v1.0.0
[05:06:21] [Server thread/INFO]: [QuantumShop] Unloaded module: Gui v1.6.0
[05:06:21] [Server thread/INFO]: [QuantumShop] Auto-save: Saved 2 online users | 0 offline users.
[05:06:21] [Server thread/INFO]: [LockettePro] Disabling LockettePro v2.9.10
[05:06:21] [Server thread/INFO]: [EliteMobs] Disabling EliteMobs v7.1.10
[05:06:21] [Server thread/INFO]: [EliteMobs] Saving EliteMobs databases...
[05:06:21] [Server thread/INFO]: [EliteMobs] All saved! Good night.
[05:06:21] [Server thread/INFO]: [AncientGates] Disabling AncientGates v2.3
[05:06:21] [Server thread/INFO]: [AncientGates] Disabled
[05:06:21] [Server thread/INFO]: [FogusCore] Disabling FogusCore v1.8.3
[05:06:21] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.1-SNAPSHOT-b777
[05:06:21] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: multiverse
[05:06:21] [Server thread/INFO]: [Elevator] Disabling Elevator v3.0.1
[05:06:21] [Server thread/INFO]: [Admin-GUI] Disabling Admin-GUI v1.4.4
[05:06:21] [Server thread/INFO]: []=====[Disabling AdminGUI]=====[]
[05:06:21] [Server thread/INFO]: |
[05:06:21] [Server thread/INFO]: | Information:
[05:06:21] [Server thread/INFO]: |
[05:06:21] [Server thread/INFO]: |   Name: AdminGUI
[05:06:21] [Server thread/INFO]: |   Developer: Black1_TV
[05:06:21] [Server thread/INFO]: |   Version: 1.4.4
[05:06:21] [Server thread/INFO]: |
[05:06:21] [Server thread/INFO]: | Support:
[05:06:21] [Server thread/INFO]: |
[05:06:21] [Server thread/INFO]: |   Discord: Crazy Rabbit#0001
[05:06:21] [Server thread/INFO]: |   Mail: ziga.zajc007@gmail.com
[05:06:21] [Server thread/INFO]: |   Discord: https://discord.gg/hUNymXX
[05:06:21] [Server thread/INFO]: |
[05:06:21] [Server thread/INFO]: []=====================================[]
[05:06:21] [Server thread/INFO]: [EnchantmentsEnhance] Disabling EnchantmentsEnhance v7.9.10
[05:06:21] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: ee
[05:06:21] [Server thread/ERROR]: Error occurred while disabling EnchantmentsEnhance v7.9.10 (Is it up to date?)
java.lang.NullPointerException: null
	at org.pixeltime.enchantmentsenhance.mysql.DataStorage.saveStats(DataStorage.java:53) ~[?:?]
	at org.pixeltime.enchantmentsenhance.Main.onDisable(Main.java:319) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:445) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:398) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:696) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864) [spigot-1.15.2-112.jar:git-Spigot-6de3d4b-fc24934]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[05:06:21] [Server thread/INFO]: [TempFly] Disabling TempFly v1.9.5
[05:06:21] [Server thread/INFO]: [TitleManager] Disabling TitleManager v2.1.6
[05:06:21] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v2.18.2
[05:06:21] [Server thread/INFO]: [CoreProtect] Finishing up data logging. Please wait...
[05:06:22] [Server thread/INFO]: [CoreProtect] Success! Disabled CoreProtect v2.18.2
[05:06:22] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.17.2.12
[05:06:22] [Server thread/INFO]: [CitizensGUI] Disabling CitizensGUI v1.1
[05:06:22] [Server thread/INFO]: [EssentialsProtect] Disabling EssentialsProtect v2.17.2.12
[05:06:22] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.2-SNAPSHOT;bf2593e
[05:06:22] [Server thread/INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[05:06:22] [Server thread/INFO]: [PlotSquared] Disabling PlotSquared v4.486
[05:06:22] [Server thread/INFO]: [McPay] Disabling McPay v2.0.0-alpha-b94
[05:06:22] [McPay Logger/INFO]: [McPay] ====== McPay > 正在注销应用 ======
[05:06:22] [Server thread/INFO]: [SuperVanish] Disabling SuperVanish v6.1.3
[05:06:22] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat v2.17.2.12
[05:06:22] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.26-SNAPSHOT (build 1842)
[05:06:22] [Server thread/INFO]: [Civs] Disabling Civs v1.6.5
[05:06:22] [Server thread/INFO]: [Civs] Civs Version: 1.6.5 is now disabled!
[05:06:22] [Server thread/INFO]: [Essentials] Disabling Essentials v2.17.2.12
[05:06:22] [Server thread/INFO]: [Vault] [Vault][Economy] Essentials Economy unhooked.
[05:06:22] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.2.0-SNAPSHOT+4910-865c3a2
[05:06:22] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[05:06:22] [Server thread/INFO]: [Companions] Disabling Companions v1.6.4
[05:06:22] [Server thread/INFO]: §6Companions§7 is disabling and saving necessary files..
[05:06:22] [Server thread/INFO]: §6  >§7 Removed §e2§7 Companion(s)..

[05:06:22] [Server thread/INFO]: §6Companions§7 by Astero§6 has been sucessfully disabled!

[05:06:22] [Server thread/INFO]: [BossShopPro] Disabling BossShopPro v2.0.8
[05:06:22] [Server thread/INFO]: [BossShopPro] Disabling... bye!
[05:06:22] [Server thread/INFO]: [Dantiao] Disabling Dantiao vH-2.0
[05:06:22] [Server thread/INFO]: [Dantiao] 单挑插件已关闭...
[05:06:22] [Server thread/INFO]: [Dantiao] DantiaoV2 by:Valorin
[05:06:22] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.1
[05:06:22] [Server thread/INFO]: [MiaoChat] Disabling MiaoChat v1.8.9-git-f22113584d750a8d95fb5df80d226af9abc4e80e
[05:06:22] [Server thread/INFO]: [Vault] Disabling Vault v1.7.2-b107
[05:06:22] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: vault
[05:06:22] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.6.2-SNAPSHOT
[05:06:22] [McPay Logger/INFO]: [McPay] ====== McPay > 应用注销成功 ======
[05:06:22] [McPay Logger/INFO]: [McPay] > 成功注销应用：注销成功
[05:06:22] [McPay Logger/INFO]: [McPay] ====== McPay > 完成 ======
[05:06:22] [McPay Logger/INFO]: [McPay] ====== McPay > 开始卸载 ======
[05:06:22] [McPay Logger/INFO]: [McPay] > 正在关闭未关闭界面玩家的界面...
[05:06:22] [McPay Logger/INFO]: [McPay] ====== McPay > 已卸载 ======
[05:06:23] [Server thread/INFO]: [CS-CoreLib] Disabling CS-CoreLib v1.6.3
[05:06:23] [Server thread/INFO]: [LangUtils] Disabling LangUtils v2.3.25
[05:06:23] [Server thread/INFO]: [LangUtils] Language Utils has been disabled.
[05:06:23] [Server thread/INFO]: [GeoFurnace] Disabling GeoFurnace v1.73
[05:06:23] [Server thread/INFO]: [GeoFurnace] GeoFurnace has been disabled
[05:06:23] [Server thread/INFO]: [PocketGames] Disabling PocketGames v3.19.1
[05:06:23] [Server thread/INFO]: [Notbuild] Disabling Notbuild v1.7
[05:06:23] [Server thread/INFO]: [Notbuild] Notbuild插件已被卸载。
[05:06:23] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1-SNAPSHOT-b447
[05:06:23] [Server thread/INFO]: [spark] Disabling spark v1.3.2
[05:06:23] [Server thread/INFO]: [VillagerOptimiser] Disabling VillagerOptimiser v1.1.2
[05:06:23] [Server thread/INFO]: [LoginSecurity] Disabling LoginSecurity v2.1.9
[05:06:23] [Server thread/INFO]: [LoginSecurity] Waiting for queued tasks...
[05:06:23] [Server thread/INFO]: [LoginSecurity] ExecutorService shut down, ready to disable.
[05:06:23] [Server thread/INFO]: [SAML] Disabling SAML v2.0.0
[05:06:23] [Server thread/INFO]: [SAML] The frozen chunk cache file has been deleted. All chunks should have been accounted for.
[05:06:23] [Server thread/INFO]: [SAML] Successfully disabled.
[05:06:23] [Server thread/INFO]: [OpenInv] Disabling OpenInv v4.0.8
[05:06:23] [Server thread/INFO]: [Chair] Disabling Chair v1.4
[05:06:23] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.0.88
[05:06:23] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[05:06:23] [Server thread/INFO]: [LuckPerms] Closing storage...
[05:06:23] [Server thread/INFO]: [LuckPerms] Goodbye!
[05:06:23] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.4.2
[05:06:23] [Server thread/INFO]: [Chenghao] Disabling Chenghao v2.2
[05:06:23] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: Chenghao
[05:06:23] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v13.7.5
[05:06:23] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.4
[05:06:23] [Server thread/INFO]: [AegisClear] Disabling AegisClear v1.5.0
[05:06:23] [Server thread/INFO]: [AegisClear] 插件已停用  作者: Aegis
[05:06:23] [Server thread/INFO]: [EntityTrackerFixer] Disabling EntityTrackerFixer v1.2.2
[05:06:23] [Server thread/INFO]: Saving players
[05:06:23] [Server thread/INFO]: jjc123 lost connection: 服务器关闭
[05:06:23] [Server thread/INFO]: jjc123 left the game
[05:06:23] [Server thread/INFO]: Cloud_Dream_Ice lost connection: 服务器关闭
[05:06:23] [Server thread/INFO]: Cloud_Dream_Ice left the game
[05:06:23] [Server thread/INFO]: Saving worlds
[05:06:23] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[05:06:23] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:06:23] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:06:23] [Server thread/INFO]: Saving chunks for level 'dipi'/minecraft:dipi
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (dipi): All chunks are saved
[05:06:23] [Server thread/INFO]: Saving chunks for level 'spawn'/minecraft:spawn
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (spawn): All chunks are saved
[05:06:23] [Server thread/INFO]: Saving chunks for level 'zy'/minecraft:zy
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (zy): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (dipi): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (spawn): All chunks are saved
[05:06:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (zy): All chunks are saved
