### ISSUE TITLE
当我打开黑石背包时将会报错

### ISSUE THREAD

**Issue by w1O42O86726** [weihao/EnchantmentsEnhance#201]
### What behaviour is observed:
What was the error?
当使用/enhance inventory时将会报错，并且无法打开
### Environment description
What server and version?
git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
### Enchantments Enhance build number:
This can be found by running `/enhance version`
7.9.10
### Error Log:
Link of the error log or stacktrace (if any, full log preferred)
[13:11:18 WARN]: [EnchantmentsEnhance] Task #11797 for EnchantmentsEnhance v7.9.10 generated an exception
java.lang.NullPointerException: null
        at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_241]
        at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_241]
        at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_241]
        at org.pixeltime.enchantmentsenhance.gui.menu.icons.ItemIcon.getOneStoneCountAsString(ItemIcon.java:18) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.icons.StoneIcon.getItem(StoneIcon.java:21) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.update(ItemMenu.java:48) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.ItemMenu.<init>(ItemMenu.java:33) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu$3.run(MainMenu.java:255) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paper.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[paper.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[paper.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[paper.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[paper.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[paper.jar:git-Paper-143]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by An-Shao** [comment]
i have the same problem ,  paper 1.15.2

**Comment by weihao** [comment]
> i have the same problem , paper 1.15.2

删除config之后重新加载还会有同样的错误吗
