### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by weihao** [weihao/EnchantmentsEnhance#219]
```
[14:44:06] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.9
org.bukkit.event.EventException: null
        at catserver.server.executor.ReflectionExecutor.execute(ReflectionExecutor.java:36) ~[ReflectionExecutor.class:git-4749966-Community]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2110) [pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectMatcher.result(FuzzyReflectMatcher.kt:176) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectFieldMatcher.resultAccessorAs(FuzzyReflectFieldMatcher.kt:126) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectFieldMatcher.resultAccessor(FuzzyReflectFieldMatcher.kt:113) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory$FIELD_ITEMSTACK_TAG$2.invoke(ItemFactory.kt:65) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory$FIELD_ITEMSTACK_TAG$2.invoke(ItemFactory.kt:47) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.getFIELD_ITEMSTACK_TAG(ItemFactory.kt) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.readTag(ItemFactory.kt:200) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.readTagSafe(ItemFactory.kt:178) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.ItemManager.readTagSafely(ItemManager.java:106) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.ItemManager.getItemEnchantLevel(ItemManager.java:128) ~[?:?]
        at org.pixeltime.enchantmentsenhance.event.Enhance.getValidationOfItem(Enhance.java:83) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:38) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at catserver.server.executor.ReflectionExecutor.execute(ReflectionExecutor.java:32) ~[ReflectionExecutor.class:git-4749966-Community]
        ... 15 more
```

**Comment by lgou2w** [comment]
CatServer? not compatible.

**Comment by weihao** [comment]
> CatServer? not compatible.
True, I did not notice it was `catserver.server`.

**Comment by weihao** [comment]
Closed, will not support CatServer
