### ISSUE TITLE
物品无法放入GUI

### ISSUE THREAD

**Issue by sky299** [weihao/EnchantmentsEnhance#223]
### Environment description
What server and version?  
1.12.2 Mohist

### Enchantments Enhance build number:  7.9.15
This can be found by running `/enhance version`

### Error Log:
[21:30:45 ERROR]: Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.15
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:1.12.2-5b88dcf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-5b88dcf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-5b88dcf]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2108) [pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:206) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectMatcher.result(FuzzyReflectMatcher.kt:176) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectFieldMatcher.resultAccessorAs(FuzzyReflectFieldMatcher.kt:126) ~[?:?]
        at com.lgou2w.ldk.reflect.FuzzyReflectFieldMatcher.resultAccessor(FuzzyReflectFieldMatcher.kt:113) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory$FIELD_ITEMSTACK_TAG$2.invoke(ItemFactory.kt:65) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory$FIELD_ITEMSTACK_TAG$2.invoke(ItemFactory.kt:47) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.getFIELD_ITEMSTACK_TAG(ItemFactory.kt) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.readTag(ItemFactory.kt:200) ~[?:?]
        at com.lgou2w.ldk.bukkit.item.ItemFactory.readTagSafe(ItemFactory.kt:178) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.ItemManager.readTagSafely(ItemManager.java:106) ~[?:?]
        at org.pixeltime.enchantmentsenhance.manager.ItemManager.getToolEnchantLevel(ItemManager.java:133) ~[?:?]
        at org.pixeltime.enchantmentsenhance.event.Enhance.getValidationOfToolItem(Enhance.java:365) ~[?:?]
        at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-5b88dcf]
        ... 14 more

**Comment by lgou2w** [comment]
**EE 不兼容 CatServer 服务端！**

**Comment by sky299** [comment]
不是CatServer，是Mohist
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoonLake"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午1:40
收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;;
抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223)





 
EE 不兼容 CatServer 服务端！

**Comment by lgou2w** [comment]
> 
> 不是CatServer，是Mohist ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"MoonLake"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月6日(星期一) 中午1:40 收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;; 抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223) EE 不兼容 CatServer 服务端！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

都是类似的服务端，不兼容的。只支持 Bukkit, Spigot, Paper 这些 ;)

**Comment by sky299** [comment]
能修复么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MoonLake"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午1:47
收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;;
抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223)





  
不是CatServer，是Mohist ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"MoonLake"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月6日(星期一) 中午1:40 收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;; 抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223) EE 不兼容 CatServer 服务端！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
都是类似的服务端，不兼容的。只支持 Bukkit, Spigot, Paper 这些 ;)

**Comment by lgou2w** [comment]
不会修复，没有打算。另见：#179

**Comment by sky299** [comment]
为什么config的语言设置改成中文后，游戏里还是英文？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weihao/EnchantmentsEnhance"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午1:52
收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;;
抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223)





 
不会修复，没有打算。另见：#179

**Comment by sky299** [comment]
BUG反馈：当物品从0级开始强化到一级的时候，强化成功物品并没有被附魔:

&nbsp;"1"
&nbsp; &nbsp; baseChance: 100
&nbsp; &nbsp; chanceIncreasePerFailstack: 0
&nbsp; &nbsp; maximumFailstackApplied: -1
&nbsp; &nbsp; failstackGainedPerFail: 1
&nbsp; &nbsp; costToForceEnchant: -1
&nbsp; &nbsp; downgradeChanceIfFail: 0.0
&nbsp; &nbsp; destroyChanceIfFail: 0.0
&nbsp; &nbsp; requireConcentratedStones: false
&nbsp; &nbsp; broadcastEnhance: false
&nbsp; &nbsp; fireworkIfSuccessful: false
&nbsp; &nbsp; fireworkRounds: 1
&nbsp; &nbsp; prefix: ""
&nbsp; &nbsp; suffix: "&amp;8+1"
&nbsp; &nbsp; enchantments:
&nbsp; &nbsp; &nbsp; WEAPON:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; &nbsp; - Random:1
&nbsp; &nbsp; &nbsp; ARMOR:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; &nbsp; - Random:1
&nbsp; &nbsp; &nbsp; PICKAXE:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; AXE:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; HOE:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; SHOEVEL:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; BOW:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; KNIFE:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; &nbsp; Rod:
&nbsp; &nbsp; &nbsp; &nbsp; - Endless:1
&nbsp; &nbsp; lore:
&nbsp; &nbsp; &nbsp; - "§8§m--------§8§l[ §c§l当前强化等级：§e1 §8§l]§8§m--------"



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weihao/EnchantmentsEnhance"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午1:52
收件人:&nbsp;"weihao/EnchantmentsEnhance"<EnchantmentsEnhance@noreply.github.com&gt;;
抄送:&nbsp;"Sky."<463731963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [weihao/EnchantmentsEnhance] 物品无法放入GUI (#223)





 
不会修复，没有打算。另见：#179
